formatting.indent_string = "    "

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "dev-dependencies", "lints"]

[rule.formatting]
reorder_arrays = true
reorder_keys = true
align_comments = false
